from __future__ import annotations

from .base import BaseProvider


class MockProvider(BaseProvider):
    """Deterministic provider for reproducible class demos.

    It does not call a real LLM. Instead, it creates predictable responses so the
    codebase can run on any computer without an API key.
    """

    def generate(self, system_prompt: str, user_prompt: str) -> str:
        lower_prompt = user_prompt.lower()

        if "plan" in lower_prompt:
            return (
                "1. Identify the main research topic.\n"
                "2. Retrieve relevant paper notes.\n"
                "3. Summarize the most important concepts.\n"
                "4. Write a short academic response.\n"
                "5. Review the response for completeness."
            )

        if "review" in lower_prompt:
            return (
                "Review passed. The response explains important ideas, gives an application "
                "scenario, and includes personal learning."
            )

        return (
            "This response was generated by the mock provider. It demonstrates the "
            "provider-agnostic structure without requiring a paid LLM API."
        )
